# ── Platform Detection ───────────────────────────────────────────────────────
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(PLATFORM_LINUX TRUE)
    add_compile_definitions(PLATFORM_LINUX)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(PLATFORM_MACOS TRUE)
    add_compile_definitions(PLATFORM_MACOS)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(PLATFORM_WINDOWS TRUE)
    add_compile_definitions(PLATFORM_WINDOWS)
endif()

# ── Architecture & SIMD Detection ───────────────────────────────────────────
if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64|i[3-6]86")
    set(ARCH_X86 TRUE)
    include(CheckCCompilerFlag)
    check_c_compiler_flag("-mavx2" COMPILER_SUPPORTS_AVX2)
    check_c_compiler_flag("-msse4.2" COMPILER_SUPPORTS_SSE42)
    if(COMPILER_SUPPORTS_AVX2)
        add_compile_definitions(HAS_AVX2)
    endif()
    if(COMPILER_SUPPORTS_SSE42)
        add_compile_definitions(HAS_SSE42)
    endif()
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm|aarch64|ARM64")
    set(ARCH_ARM TRUE)
    add_compile_definitions(HAS_NEON)
endif()

# ── Rendering Dependencies (when enabled) ───────────────────────────────────
if(ENABLE_RENDERING)
    find_package(OpenGL)
    if(OpenGL_FOUND)
        add_compile_definitions(HAS_OPENGL)
    endif()
endif()
